actions:
  black:
    run: .venv/bin/black --check {files}
    fix: .venv/bin/black {files}
    include: "*.py"
    exclude:
      - .venv/

  flake8:
    run: .venv/bin/flake8 {files}
    include: "*.py"
    exclude:
      - .venv/
