on:
  push:
    branches:
      - master
  pull_request:

name: Code Lint
jobs:
  chore:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install virtualenv
        run: |
          pip install virtualenv
          make install-dev

      - name: Print environment
        run: |
          source .venv/bin/activate
          python --version
          pip --version

      - name: Lint
        run: |
          make lint
